using System.Collections.Generic;
using System.Text;

namespace Neo.UIKit.Editor
{
    /// <summary>
    /// Emits UiIds.g.cs: compile-safe constants for page ids, element paths, popup paths and
    /// counter ids. A rename in the design becomes a compile error instead of a silent failure.
    /// </summary>
    public static class UiIdsGenerator
    {
        /// <summary>Emits the UiIds.g.cs content for all planned pages.</summary>
        public static string Generate(IReadOnlyList<UiPagePlan> plans, UiKitGenerationSettings settings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by Neo.UIKit. Manual changes will be lost on the next generation.");
            sb.AppendLine("// </auto-generated>");
            ViewCodeGenerator.AppendNamespaceOpen(sb, settings);
            sb.AppendLine("    /// <summary>Generated page ids, element paths, popup paths and counter ids.</summary>");
            sb.AppendLine("    public static class UiIds");
            sb.AppendLine("    {");

            var usedClassNames = new HashSet<string> { "UiIds", "Counters" };
            bool firstPage = true;
            foreach (UiPagePlan plan in plans)
            {
                if (!firstPage)
                    sb.AppendLine();
                firstPage = false;

                string pageClass = NameSanitizer.Unique(NameSanitizer.ToPascalIdentifier(plan.Model.PageId), usedClassNames);
                sb.AppendLine($"        /// <summary>Paths of the \"{plan.Model.PageId}\" page.</summary>");
                sb.AppendLine($"        public static class {pageClass}");
                sb.AppendLine("        {");
                sb.AppendLine($"            /// <summary>Page id for the router.</summary>");
                sb.AppendLine($"            public const string Id = \"{plan.Model.PageId}\";");

                foreach (UiFieldPlan field in plan.Fields)
                {
                    sb.AppendLine();
                    sb.AppendLine($"            /// <summary>{field.Element.Widget} \"{field.Element.Name}\".</summary>");
                    sb.AppendLine($"            public const string {field.FieldName} = \"{field.Element.FullPath}\";");
                }

                foreach (UiPopupPlan popup in plan.Popups)
                {
                    sb.AppendLine();
                    sb.AppendLine($"            /// <summary>Paths inside popup \"{popup.Model.Name}\".</summary>");
                    sb.AppendLine($"            public static class {popup.FieldName}");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                /// <summary>Popup path for UiKit.Popups.</summary>");
                    sb.AppendLine($"                public const string Path = \"{popup.Model.FullPath}\";");
                    foreach (UiFieldPlan field in popup.Fields)
                    {
                        sb.AppendLine();
                        sb.AppendLine($"                /// <summary>{field.Element.Widget} \"{field.Element.Name}\".</summary>");
                        sb.AppendLine($"                public const string {field.FieldName} = \"{field.Element.FullPath}\";");
                    }

                    sb.AppendLine("            }");
                }

                sb.AppendLine("        }");
            }

            List<KeyValuePair<string, string>> counters = CollectCounters(plans);
            if (counters.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        /// <summary>Counter ids used with UiKit.Counters.</summary>");
                sb.AppendLine("        public static class Counters");
                sb.AppendLine("        {");
                bool firstCounter = true;
                foreach (KeyValuePair<string, string> counter in counters)
                {
                    if (!firstCounter)
                        sb.AppendLine();
                    firstCounter = false;
                    sb.AppendLine($"            /// <summary>Counter \"{counter.Value}\".</summary>");
                    sb.AppendLine($"            public const string {counter.Key} = \"{counter.Value}\";");
                }

                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            ViewCodeGenerator.AppendNamespaceClose(sb, settings);
            return sb.ToString();
        }

        /// <summary>Collects distinct counter ids from all pages as (constName, id) pairs.</summary>
        public static List<KeyValuePair<string, string>> CollectCounters(IReadOnlyList<UiPagePlan> plans)
        {
            var ids = new SortedSet<string>(System.StringComparer.Ordinal);
            foreach (UiPagePlan plan in plans)
            {
                foreach (UiFieldPlan field in plan.Fields)
                {
                    if (!string.IsNullOrEmpty(field.Element.CounterId))
                        ids.Add(field.Element.CounterId);
                }

                foreach (UiPopupPlan popup in plan.Popups)
                {
                    foreach (UiFieldPlan field in popup.Fields)
                    {
                        if (!string.IsNullOrEmpty(field.Element.CounterId))
                            ids.Add(field.Element.CounterId);
                    }
                }
            }

            var used = new HashSet<string>();
            var result = new List<KeyValuePair<string, string>>();
            foreach (string id in ids)
                result.Add(new KeyValuePair<string, string>(NameSanitizer.Unique(NameSanitizer.ToPascalIdentifier(id), used), id));

            return result;
        }
    }
}
